server:
  port: 8084

spring:
  application:
    name: temperature-processing

  profiles:
    active: dev

app:
  kafka:
    topics:
      temperature-raw: temperature.raw.v1
      temperature-processed: temperature.processed.v1