spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/temperature_processing
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: temperature-processing-dev
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.algasensors.*"
        spring.json.value.default.type: com.algasensors.temperature.processing.infra.messaging.dto.TemperatureMessage

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    root: INFO
    org.springframework.kafka: INFO
    com.algasensors: DEBUG