spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/temperature_monitoring
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: temperature-monitoring
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.algasensors.*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.algasensors.temperature.monitoring.infra.messaging.dto.TemperatureProcessedEvent

app:
  kafka:
    topics:
      processed-reading: sensor.temperature.processed.v1
