server:
 port: 8082

spring:
 application:
  name: temperature-monitoring

 rabbitmq:
  host: localhost
  port: 5672
  username: rabbitmq
  password: rabbitmq
  listener:
   simple:
    concurrency: 2
    max-concurrency: 2
    prefetch: 4
    retry:
     enabled: true
     initial-interval: 1000
     multiplier: 2
     max-interval: 10000
     max-attempts: 3

app:
 rabbitmq:
  queues:
   temperature-processing: temperature-processing.queue
   temperature-alert: temperature-alert.queue
  exchanges:
   temperature: temperature.exchange
  routing-keys:
   temperature-processing: temperature.processing
   temperature-alert: temperature.alert