apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature-monitoring
  namespace: algasensors

spec:
  replicas: 1

  selector:
    matchLabels:
      app: temperature-monitoring

  template:
    metadata:
      labels:
        app: temperature-monitoring

    spec:
      containers:
        - name: temperature-monitoring

          image: algasensors/temperature-monitoring:dev
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8083

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s

---
apiVersion: v1
kind: Service
metadata:
  name: temperature-monitoring
  namespace: algasensors

spec:
  selector:
    app: temperature-monitoring

  ports:
    - port: 8083
      targetPort: 8083
