server:
  port: 8082

spring:
  application:
    name: sensor

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  kafka:
    topics:
      raw-reading: sensor.temperature.raw.v1

  temperature:
    processing:
      url: http://localhost:8084


